"""renames for clarity

Revision ID: da47414ef185
Revises: e989dc0a4660
Create Date: 2023-08-09 14:21:38.682227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da47414ef185'
down_revision = 'e989dc0a4660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_author', sa.String(), nullable=True))
        batch_op.drop_column('author')

    with op.batch_alter_table('dayratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_author', sa.String(), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dayratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('rating_author')

    with op.batch_alter_table('bookratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('rating_author')

    # ### end Alembic commands ###
